### ISSUE TITLE
image

### ISSUE THREAD

**Issue by Zakaria-Farahi** [AbderrahimeEl/my-webSite#8]
image is too small

**Comment by Zakaria-Farahi** [comment]
![image](https://github.com/AbderrahimeEl/my-webSite/assets/124200547/12444541-8fbe-4512-9ccb-e493d1afd3f2)

**Comment by AbderrahimeEl** [comment]
that image should not be displayed in that screen size
thank you

**Comment by AbderrahimeEl** [comment]
well done
